version: '3'

services:
  db:
    build: .
    volumes:
      - pg:/var/lib/postgresql/data
      - data:/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=reviewsdb
    ports:
      - "5432:5432"
  server:
    build: ../../
    volumes:
      - pg:/var/lib/postgresql/data
      - data:/usr/src/app/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=reviewsdb
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure
volumes:
  pg:
    driver: local
  data:
    driver: local