version: '3'

services:
  db:
    build: .
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
  server:
    build: ../../
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - "5000:5000"
    links:
      - db:db
    depends_on:
      - db
    restart: on-failure